[versions]
agp = "8.4.0"
kotlin = "2.0.0"
compose = "1.6.0"
lifecycle = "2.7.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
