[versions]
agp = "8.3.0"
kotlin = "1.9.22"
compose-compiler = "1.5.10"
compose-bom = "2024.04.00"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.7.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.8.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
